### ISSUE TITLE
Convite para Organização

### ISSUE THREAD

**Issue by caue-alves** [thmPedro/AssistenteBovespa#1]
Olá @thmPedro, eu e meu amigo @Felipe-Souza-Pereira-Lima estamos temos uma organização chamada @Dsa-Software, onde construímos softwares de forma open-source e voluntária. Estamos com um projeto chamado Economist, projeto que captura informações da bolsa e o sintetiza em planilhas através de uma GUI. Como você tem conhecimento em python e aparentemente a Bolsa, gostaríamos de convidá-lo para contribuir, onde todos ganharíamos com uma equipe maior e novos aprendizados. Caso aceite irei te convidar pelas orgs @Dsa-Terminal e @Dsa-Software, organizações onde estão nossos projetos.

**Comment by thmPedro** [comment]
Obrigado pelo convite, mas não posso aceitar. Já praticamente não mexo com programação.

Obrigado novamente e bom trabalho com o projeto.

**Comment by caue-alves** [comment]
Ok, obrigado
